openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: "/"
paths:
  /login:
    post:
      operationId: "app.api.v1.auth.login"
      tags:
        - "Auth"
      summary: "Authenticate a user and generate a JWT token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: "string"
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: mypassword
              required:
                - email
                - password
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  user:
                    type: object
                    example: {
                      "auth_level": "manager",
                      "email": "user@example.com",
                      "full_name": "Test User",
                      "uid": "640f0743920ac97feb47b462"
                    }
        "401":
          $ref: "#/components/responses/UnauthorizedError"
#  /logout:
#    post:
#      summary: "Invalidate a JWT token and log out a user"
#      security:
#        - bearerAuth: []
#      responses:
#        "204":
#          description: Successful logout
#        "401":
#          $ref: "#/components/responses/UnauthorizedError"
#
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: "Unauthorized access. Invalid or missing authentication token."
